const actionTypes = {
	  FETCH_POSTS_REQUESTED: 'FETCH_POSTS_REQUESTED'
	, FETCH_POSTS_REJECTED: 'FETCH_POSTS_REJECTED'
	, FETCH_POSTS_FULFILLED: 'FETCH_POSTS_FULFILLED'
	, SIGNIN_REQUESTED: 'SIGNIN_REQUESTED'
	, SIGNIN_REJECTED: 'SIGNIN_REJECTED'
	, SIGNIN_FULFILLED: 'SIGNIN_FULFILLED'
	, ADD_POST_REQUESTED: 'ADD_POST_REQUESTED'
	, ADD_POST_REJECTED: 'ADD_POST_REJECTED'
	, ADD_POST_FULFILLED: 'ADD_POST_FULFILLED'
	, UPLOAD_FILE_REQUESTED: 'UPLOAD_FILE_REQUESTED'
	, UPLOAD_FILE_REJECTED: 'UPLOAD_FILE_REJECTED'
	, UPLOAD_FILE_FULFILLED: 'UPLOAD_FILE_FULFILLED'
	, UPLOAD_FILE_DISPLAYED: 'UPLOAD_FILE_DISPLAYED'
}

export default actionTypes;