const actionTypes = {
	  FETCH_POSTS_REQUESTED: 'FETCH_POSTS_REQUESTED'
	, FETCH_POSTS_REJECTED: 'FETCH_POSTS_REJECTED'
	, FETCH_POSTS_FULFILLED: 'FETCH_POSTS_FULFILLED'
	, SIGNIN_REQUESTED: 'SIGNIN_REQUESTED'
	, SIGNIN_REJECTED: 'SIGNIN_REJECTED'
	, SIGNIN_FULFILLED: 'SIGNIN_FULFILLED'
	, SIGNOUT: 'SIGNOUT'
}

export default actionTypes;